language: node_js
node_js:
  - 6
  - 8
  - 10
services: elasticsearch
before_install:
  - sudo service elasticsearch stop
  - sudo apt-get upgrade elasticsearch
after_install:
  - npm run test:functional
